### ISSUE TITLE
will you share the trained checkpoints?

### ISSUE THREAD

**Issue by movingright** [ken2576/pvp#1]
Hi, thanks for the cool repo, your results look great. Do you have plans of sharing the trained checkpoint files? If yes, when?

**Comment by ken2576** [comment]
Hi,

Thanks for your inquiry.
Yes! I am planning to release the checkpoint.
In fact, you can access them here.
https://drive.google.com/drive/folders/1aHDWOqW0FE0E5HD6A84sYxAe9BBRYbr_?usp=sharing

I have yet to write proper documentation since I am busy moving to a different location at the moment.
The checkpoints correspond to the dataset mentioned in our paper. You might need to download their data and run the NHA preprocessing as mentioned in this repo's README.

Please let me know if there is any other question. I am also trying to add a Jupyter Notebook demo at some point.

**Comment by movingright** [comment]
That's helpful, thank you. :)
